### ISSUE TITLE
Add "test on safety" flag on People page

### ISSUE THREAD

**Issue by Zubyte** [WEEE-Open/crauto#11]
Until now, we had a reasonably good chance to know if a person passed the DISAT safety test from the status of its account (locked / not locked). Recently, due to the COVID-19 emergency, we started activating the accounts before the test on safety is passed, to allow people to access team services remotely.

Even though in each personal tab there is a "date of the test on safety" field, I suggest adding a visual flag (tick) on the People overview page, to have a quick way of obtaining this information.

**Comment by lvps** [comment]
@Zubyte Also add a flag for "has telegram ID or  telegram username"

**Comment by lvps** [comment]
@Zubyte And use the table library thing from weeehire
